# Generated by Django 3.1.2 on 2021-02-04 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=50)),
                ('registration', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='center.registration')),
            ],
            options={
                'verbose_name': 'RegistrationDetails',
                'verbose_name_plural': 'RegistrationDetails',
            },
        ),
    ]
