# Generated by Django 3.1.6 on 2021-02-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0008_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient',
        ),
    ]
