# Generated by Django 3.1.6 on 2021-02-05 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0009_delete_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='investigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='center.investigation'),
        ),
    ]
